[project]
name = "investsmartexport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cerberus>=1.3.7",
    "pyyaml>=6.0.2",
    "sc-utility>=1.3.0",
    "selenium>=4.32.0",
]
